[package]
name = "cleancode"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
regex = "1.5"
indicatif = "0.16"
colored = "2.0"
uuid = { version = "1.1", features = ["v4"] }
chrono = "0.4"